# Generated by Django 3.2.12 on 2023-06-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('cpf', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('street', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=10)),
                ('number', models.IntegerField()),
                ('apartment', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
