# Generated by Django 3.2.12 on 2023-07-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_oficina', '0002_manutencao_peca_veiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('street', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=9)),
                ('number', models.IntegerField()),
                ('apartment', models.CharField(blank=True, max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('workhours', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='id',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='license_plate',
            field=models.CharField(default=None, max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
