# Generated by Django 3.2.12 on 2023-07-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_oficina', '0003_auto_20230701_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manutencao',
            old_name='data',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='manutencao',
            old_name='mecanico',
            new_name='mechanic',
        ),
        migrations.RenameField(
            model_name='manutencao',
            old_name='veiculo',
            new_name='vehicle',
        ),
        migrations.RemoveField(
            model_name='manutencao',
            name='comentarios',
        ),
        migrations.RemoveField(
            model_name='manutencao',
            name='km',
        ),
        migrations.AddField(
            model_name='manutencao',
            name='Km',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manutencao',
            name='comments',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='peca',
            name='quantidade',
            field=models.IntegerField(),
        ),
    ]
