# Generated by Django 3.2.12 on 2023-07-01 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_oficina', '0004_auto_20230701_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manutencao',
            name='mechanic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_oficina.mecanico'),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_oficina.veiculo'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_oficina.cliente'),
        ),
    ]
