# Generated by Django 3.2.12 on 2023-07-02 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_oficina', '0006_rename_km_manutencao_km'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='mechanic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_oficina.mecanico', to_field='name'),
        ),
        migrations.AlterField(
            model_name='mecanico',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_oficina.cliente', to_field='name'),
        ),
    ]
