# Generated by Django 3.2.12 on 2023-07-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_oficina', '0007_auto_20230702_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manutencao',
            name='mechanic',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='vehicle',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='owner',
            field=models.CharField(max_length=100),
        ),
    ]
