# Generated by Django 3.2.12 on 2023-07-02 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_oficina', '0008_auto_20230702_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manutencao',
            old_name='km',
            new_name='Km',
        ),
    ]
